---
output: 
  bookdown::pdf_document2:
    toc: false
    citation_package: natbib
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
title: "Institutional Constraints and Fiscal Policy Stability"
author: 
- Hao Wang
- Arizona State University
 
date: '`r format(Sys.Date(), "%B %d, %Y")`'


abstract: "This manuscript tests two competing hypotheses of economic growth, performance evaluation and political support. According to the economic explanation of modernization theory, rapid economic growth fosters income inequality, and the poor will then demand political reform and redistribution of wealth. On the other hand, the cultural approach of modernization argues that socio-economic development changes value systems and people's ability to think critically. As a result, those people with higher levels of cognitive ability and political awareness will favor democracy in a authoritarian context. Meanwhile, Economic Voting literature argue that people value government's socio-economic performance, consequently they will support/oppose the incumbent government based on their evaluation. This study uses a general opinion survey in China to test these two competing hypotheses. My results show that cultural modernization mechanism is robust in all models."
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: single
papersize: letter
bibliography: D:/Dropbox/bib/Haowang.bib
biblio-style: apsr
citecolor: blue
---

**Key Words**: Political Support, Economic Growth, Government Performance, China

\newpage


# Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Since the Reform and Opening policy in 1978, China has undergone remarkably changes in economy, social structures and political structures. According to World Bank, China's GDP per capita increases from 154.97 USD in 1978 to 6807.43 USD in 2013, and World Bank has classified China as a middle income country. Dramatically changes in economic development secures Chinese Communist Party's (CCP) dominance in the post-Mao era [@HolbigGilley2010], many Chinese citizens express "special gratitude" to CCP for the remarkable increase of economy as well as their living standards. On the other hand, CCP justifies the authoritarian rule as "the only possible and correct path" for Chinese people's sake, "Western Democracies are not suitable in China" [@YangChen2013 @Pei2012].

Stable authoritarian ruling accompanied by rapid economic growth makes China a unique case in comparative politics. On one hand, economic development have dramatically shifted people's lifestyles: ordinary citizens can now afford modern appliances such as TV sets, computers, washing machines, automobiles etc., and many Chinese families can even send their children abroad for better education. Many scholars thus conclude that Chinese people are in favor of the strong nondemocratic governance because of rapid economic growth [@ChenDickson2008]. On the other hand, economic growth does not unilaterally increase political support. @Huntington2008 made the famous argument that rapid economic growth often comes with dramatically changes of society, which brings about regime instability. With respect to the China case, economic growth brings about noticeable gaps between the rich and poor, government officials and the common citizens. Many Chinese citizens express their dissatisfaction of inequality, limited degrees of political rights and freedom of speech online [@King2013 @Mackinnon2011 @PanXu2015]. Protests on land reform and housing are not unusual titles in Chinese media [@Li2008 @Kennedy2010].

According to Modernization theory (Lipset 1959, 1993), economic growth will foster urbanization, industrialization, increasing levels of education and income, and as a result it will increase political participation and demand for democracy. Although the mechanism is challenged by Przeworski and Limongi (1997), still there is a general pattern between economic modernization and democracy. Since economic development not only changed Chinese citizen's physical well-beings but also cognitive ideas, it is worthwhile to test the relation between economic development and political attitudes towards a nondemocratic government (Zhai 2015).

On the other hand, retrospective evaluation theory holds that citizens value the economic performance of the government and vote accordingly (Lewis-Beck and Stegmaier 2000).  Although previous economic voting studies are based on democratic elections, there is no significant reason that citizens living in authoritarian countries would NOT value government performance. In fact, Lewis-beck et al. (2014) show that the vote-popularity function can be applied to nondemocratic settings like China. Therefore, instead of the negative relationship between economic development and demand for democracy; retrospective evaluation theory holds that good government performance will yield solid political support.


??Two different sets of stories here: relative deprivation?? MLM

???No need for this This project differs from the previous public opinion studies in that I incorporate provincial economic growth data into individual level surveys. Because there are significant variations of economic growth rates in different provinces, this allows me to test the two competing hypotheses simultaneously. Overall, this manuscript is trying to disentangle the relation between economic development and political attitudes in a nondemocratic environment.


\nocite{Zhai2015,Lipset1993,Lipset1959,Lewis-Beck2000,Pan2015,Wallace2016}
\nocite{WorldBank1,WorldBank2,Lewis-Becketal2014,Truex2014,Przeworski1997,Tsai2010,Meng2014,Huta2014}
\nocite{Rabe-Heskethetal2005,Rabe-Heskethetal2004,Lorentzen2014,Wintrobe1998,Boix2003a}







# Theory and Hypotheses

## Modernization Theory

Modernization theory holds that social-economic development includes a multi-stage process towards democracy. Accordingly, economic development will bring about higher levels of literacy, education, higher income and better living standards. It is argued that when people are economically better off, they will engage in many political activities and struggle for more political rights. This general pattern received some weak empirical support (such as Boix and Stokes 2003), but it has also been criticized for its unclear causal mechanism. Later Scholars refine modernization theory and propose two general causal mechanisms linking modernization and democratization together: through inequality and redistribution of wealth and through the transition of culture and values.

In the elite-citizen game-theory model, inequality plays the pivotal role in determining the potential probability of democratic transition (Acemoglu and Robinson 2005. Boix 2003). Boix (2003) argues that high inequality levels will increase citizens' dissatisfaction on government and increase demand for political reform. According to Kuznets (1955), rapid economic growth
often comes with increasing gap of income inequality. And as a result of enlarging income inequality, people will demand political reform and redistribution. 
Therefore, we have:
\nocite{Acemoglu2005}

\begin{quotation}
	Hypothesis 1 (Inequality): Rapid economic growth increases income gap, and consequently triggers people's demand for political democracy.
\end{quotation}

Cultural explanations of modernization theory focus on the changes in the social and cultural realms. It argues that modernization process enhances people's cognitive ability and critical thinking. Besides, the dramatic social-economic changes may influence previous value systems as well (Welzel et al. 2003). This explanation received support in political behavior and political psychology studies (e.g. Geddes and Zaller 1989, Zaller 1992, Truex 2014). With respect to the China case, Scholars also found empirical support for the Changing pattern of Chinese value system and ideology (Pan and Xu 2015, Yang and Tang 2010, Zhong and Chen 2013). Since authoritarian rules highlights obedience and respect to authority, it is inherently incompatible with critical thinking and self-expression values. A natural consequence is that people who think critically tend to be dissatisfied with authoritarian ruling:

\begin{quotation}
	Hypothesis 2 (Critical Thinking): Modernization process increases citizens' ability of thinking critically (about politics), consequently they will demand more political rights and higher levels of liberty.
\end{quotation}
\nocite{Kuznets1955,Welzeletal2003}
\nocite{Acemoglu2005,Boix2003}


\subsection{`Economic Voting' Theory}
Unlike modernization theory which depicts the path to democracy as a unidimensional route, "economic voting" literature model political support as a function of government performance, especially on economic and social issues (Lewis-Beck and Stegmaier 2000). Although citizens in a authoritarian country do not vote the way in democracies, they can express their opinions in informal ways. For instance, in a village-level field Lily Tsai identifies that accountability exists in rural China (Tsai 2007). Therefore, a natural hypothesis is that people who highly evaluate government performance in socio-economic issues tend to support the incumbent elites. Unfortunately, the data structure I have does not contain important questions on socio-tropic evaluation; nevertheless, the CGSS 2003 survey includes related questions on `pocket book' voting, respondents were asked to compare their income and living condition to 3 years ago/5 years ago and 10 years ago, as well as prospective evaluation (compare with what it may be 3 years/5 year/10 years later). Consequently we have the following two hypotheses:



<!--This doesn't seem relevant.-->

\begin{quotation}
	Hypothesis 3 (Retrospective Evaluation): Citizens whose economic condition increased/decreased over the past years tend to support incumbent governance/political reforms
\end{quotation}

\begin{quotation}
	Hypothesis 4 (Prospective Evaluation): Citizens who expect their economic condition will increase/decrease in the future years tend to support incumbent governance/political reforms
\end{quotation}

Overall, I highlight four possible mechanisms linking economic development with political support.
<!--Modernization hypothesis is developed exclusively in explaining regime transitions. -->
On the other hand, `Economic Voting' literature comes from experiences in Western democracies.
 According to Przeworski and Limongi (1997), China should be in transition to democracy as it has passed the "transition bar" of $4000. However, China seems to be a stable autocracy now and since CCP is in control of the military, a coup is unlikely. On the other hand, one might doubt the applicability of "Economic Voting" theory in a nondemocratic context: can authoritarian leaders generate political support by rapid economic development? This study provides a test for both theories based on survey data in China as well as provincial level economic growth indicators.
  

\nocite{Tsai2007a}



# Data

Individual level data is from the 2006 China General Social Survey (CGSS). CGSS is a annual/biannual survey of China's urban and rural households and it started at 2003. Comparing with other surveys such as China Value 
and Ethnic Survey (featured in Yang and Tang 2010) and World Value Survey, CGSS comes with a more representative sample and much larger observations. The survey was administered by Renmin University and other regional institutions in China. In 2006, the survey was conducted between September and November, 10151 households in 28 provinces (out of 31) were interviewed. Although this survey did not focus on citizens' political opinion, it nevertheless provide questions directly and indirectly reflecting people's political preferences (Jiang and Yang 2015). Response rate in the 2006 survey was about 51.10% and the missing value rate was about 3.41%.

